#+TITLE: Useful Physics Formulae
#+AUTHOR: Stefan Countryman
#+EMAIL: stefan.countryman@gmail.com
#+OPTIONS: tex:dvisvgm

* Kinematics

  There are only two equations you should memorize from kinematics.

** Position

   #+BEGIN_EXPORT latex
   $$
   x = \frac{1}{2} a t^2 + v_0 t + x_0
   $$
   #+END_EXPORT

** Speed

   #+BEGIN_EXPORT latex
   $$
   v = a t + v_0
   $$
   #+END_EXPORT

* Energy

** Conservation of energy

   /Explanation:/ The final total energy of a system (the sum of all kinetic
   #+BEGIN_EXPORT latex
   ($K_f$)
   #+END_EXPORT
   and potential
   #+BEGIN_EXPORT latex
   ($U_f$)
   #+END_EXPORT
   energy terms) will be exactly the same as the initial total
   energy plus the work
   #+BEGIN_EXPORT latex
   ($W$)
   #+END_EXPORT
   done on the system by an external force.

   #+BEGIN_EXPORT latex
   $$
   \Sigma U_i + \Sigma K_i + W = \Sigma U_f + \Sigma K_f
   $$
   #+END_EXPORT

** Work done by a force

   /Explanation:/ If a force acts on an object while the object is moving,
   #+BEGIN_EXPORT latex
   then the work done on the object is just the product of the force $F$,
   the total distance traveled $d$, and the cosine of the angle between
   the displacement and the force ($\theta$). This is true even if the motion
   was not in a straight line; $d$ is just the total change in position.

   $$
   W = F d cos(\theta)
   $$
   #+END_EXPORT

** Relationship between work and potential energy

   /Explanation:/ The work done by a conservative force is simply the change in
   *potential energy*, albeit with a negative sign in front (since the energy
   /lost/ by the potential is /gained/ by the system, or vice versa).

   #+BEGIN_EXPORT latex
   $$
   W = -\Delta U = - (U_f - U_i)
   $$
   #+END_EXPORT

* Springs

** Force (Hooke's Law)

   /Explanation:/
   #+BEGIN_EXPORT latex
   The force due to a spring is proportional to the spring constant $k$ and the
   displacement from equilibrium $x$. The negative sign comes from the fact that
   springs always want to return to their equilibrium length when disturbed; a
   positive displacement $x$ will therefore result in a force $F_s$ in the negative
   direction. A stiffer spring will have a larger spring constant $k$.

   $$
   F_s = - k x
   $$
   #+END_EXPORT

** Potential Energy

   /Explanation:/
   #+BEGIN_EXPORT latex
   Again, $k$ is the spring constant and $x$ is the displacement from equilibrium.

   $$
   U_s = k x^2
   $$
   #+END_EXPORT

* Momentum

** Center of Mass
** Definition of Impulse
** Impulse in terms of Force
** Definition of Momentum
** Conservation of Momentum
** Elastic collision equations

* Rotation

  Notice that the /translational/ variables for position, speed, and acceleration
  #+BEGIN_EXPORT latex
  are all just $R$ times the corresponding
  #+END_EXPORT
  /rotational/ variables:
  #+BEGIN_EXPORT latex
  angle ($\theta$), speed ($\omega$), and angular acceleration ($\alpha$).
  #+END_EXPORT

** Position

   #+BEGIN_EXPORT latex
   $$
   \Delta x = R \Delta \theta
   $$
   #+END_EXPORT

** Speed

   #+BEGIN_EXPORT latex
   $$
   v = R \omega
   $$
   #+END_EXPORT

** Acceleration

   #+BEGIN_EXPORT latex
   $$
   a = R \alpha
   $$
   #+END_EXPORT

** Torque vs. Force

   #+BEGIN_EXPORT latex
   $$
   \tau = F r sin \theta
   $$
   #+END_EXPORT

** Moment of Inertia

   #+BEGIN_EXPORT latex
   Moment of Inertia $I$ is like mass $m$ in translational motion. There are
   different formulas for different shapes, but otherwise it behaves just like
   the mass: the bigger it is, the greater the force/torque you need to
   accelerate the object.
   #+END_EXPORT

** Angular Momentum

   #+BEGIN_EXPORT latex
   Angular momentum $L$ is like momentum $p$.
   #+END_EXPORT

** Centripetal Acceleration

   #+BEGIN_EXPORT latex
   $$
   a_{centripetal} = \frac{v^2}{r}
   $$
   #+END_EXPORT

** Parallel Axis Theorem

   #+BEGIN_EXPORT latex
   $$
   I = I_{CM} + M d^2
   $$
   #+END_EXPORT


* Gravitation

  It's just conservation of energy, summing forces, and circular motion plus a
  new equation for /force/ and a new equation for /potential energy/.

** Force (Newton)

   #+BEGIN_EXPORT latex
   $$
   F_g = \frac{G m_1 m_2}{r^2}
   $$
   #+END_EXPORT

** Potential Energy

   #+BEGIN_EXPORT latex
   $$
   U_g = - \frac{G m_1 m_2}{r}
   $$
   #+END_EXPORT

** Gravitational Acceleration (g vs. G)

   #+BEGIN_EXPORT latex
   This is just the acceleration due to gravity; we have been using the value
   at Earth's surface, $g = 9.8 m/s$. In the below equation, $M$ is the mass of
   the large object (like the earth) and $r$ is the distance to the center of
   the large object. Notice that this is just the same as the force due to
   gravity, $F_g$, but without the smaller mass.

   $$
   g = \frac{G M}{r^2}
   $$
   #+END_EXPORT

** Kepler's Laws

   Don't worry about these for now. They are less important. We can discuss them
   a bit tomorrow.
